=== albanoj2/EagleSwag/EagleSwag/assets/config/sqlite/dbTableMappings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="mappings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="map" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="class" maxOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="package" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="table" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="class" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="package" type="xs:string" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="constant" maxOccurs="1" />
										<xs:element name="explicitName" minOccurs="0" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== albanoj2/EagleSwag/EagleSwag/assets/config/sqlite/dbTableMappings.xml
<?xml version="1.0" encoding="UTF-8" ?>
<mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dbTableMappings.xsd">
    
    <!-- General questions table -->
    <map>
        <class package="com.oceans7.mobileapps.eagleswag.domain">GeneralQuestion</class>
        <table>
            <class package="com.oceans7.mobileapps.eagleswag.persistence.sqlite">SQLiteDataControllerConstants</class>
            <constant>GENERAL_QUESTIONS_TABLE</constant>
        </table>
    </map>
    
    <!-- Engineering questions table -->
    <map>
        <class package="com.oceans7.mobileapps.eagleswag.domain">EngineeringQuestion</class>
        <table>
            <class package="com.oceans7.mobileapps.eagleswag.persistence.sqlite">SQLiteDataControllerConstants</class>
            <constant>ENGINEERING_QUESTIONS_TABLE</constant>
        </table>
    </map>
    
    <!-- Pilot questions table -->
    <map>
        <class package="com.oceans7.mobileapps.eagleswag.domain">PilotQuestion</class>
        <table>
            <class package="com.oceans7.mobileapps.eagleswag.persistence.sqlite">SQLiteDataControllerConstants</class>
            <constant>PILOT_QUESTIONS_TABLE</constant>
        </table>
    </map>
</mappings>
